### ISSUE TITLE
import sys in pcs_resource.py

### ISSUE THREAD

**Issue by lefan** [OndrejHome/ansible.pcs-modules-2#12]
It looks like missed `import sys` in  pcs_resource.py

**Comment by OndrejHome** [comment]
Hi @lefan, Than you for reporting this issue! 
I have pushed the change in tag `v14`. However out of curiosity could you please let me know which version of Ansible and Python you are using? (output from `ansible --version`). On my 2 machines I have Ansible 2.5.5 and one with python 2.7.14 doesn't need this import while the other with python 3.6.5 fails with the missing sys module.

**Comment by lefan** [comment]
Hi @OndrejHome .

```
ansible 2.4.2.0
  config file = /home/lefan/.ansible.cfg
  configured module search path = [u'/home/lefan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

**Comment by OndrejHome** [comment]
Thank you @lefan for feedback! 
I will keep this open for a bit as I need to figure out how to test for similar stuff in future. The test I use now is ineffective for this and it would definitely deserve some proper test to catch this kind of errors.

**Comment by OndrejHome** [comment]
As there are multiple issues that were resolved I have moved the idea of better testing into #16 . Closing this one now as it is part of `master` branch (v14). Thank you for reporting!
