### ISSUE TITLE
Changing a resource

### ISSUE THREAD

**Issue by moserhans** [OndrejHome/ansible.pcs-modules-2#5]
I created a simple test cluster.
A add a resource:

```
  - name: ensure resource 'ClusterIP' of 'IPaddr2' type exists an has 30 second monitor interval
    pcs_resource: name='ClusterIP' resource_type='IPaddr2' options='ip=172.30.8.199 op monitor interval=30'
```
Works fine.
I change the resource - like the interval:
```
  - name: ensure resource 'ClusterIP' of 'IPaddr2' type exists an has 30 second monitor interval
    pcs_resource: name='ClusterIP' resource_type='IPaddr2' options='ip=172.30.8.199 op monitor interval=22230'
```
The playbook now fails:

`failed: [cluster2.example.com] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1516797934.68-219244836886194/pcs_resource", line 1860, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1516797934.68-219244836886194/pcs_resource", line 201, in main
    rc, diff = compare_resources(module, resource, clean_resource)
  File "/root/.ansible/tmp/ansible-tmp-1516797934.68-219244836886194/pcs_resource", line 110, in compare_resources
    'before': to_native(b('').join(n3_file.readlines())),
NameError: global name 'to_native' is not defined
OpenSSH_6.6.1, OpenSSL 1.0.1i-fips 6 Aug 2014
debug1: Reading configuration data /home/foo/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 20: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to cluster2.example.com closed.
`

ansible 1.9.4 (yeah, I know …) on SLES host
CentOS 7 latest for the cluster

**Comment by OndrejHome** [comment]
Hi @moserhans. This looks interesting. On first look this may be an issue with code that compares the resources. This is different from code that just creates the resource. 1. Would you be able to confirm if the following would succeed in your systems?
- create resource with monitor 30
- delete the resource
- create resource with monitor 22230

2. Does the same error appear when you use the '--check' in scenario you have described?

I would have setup some system with older ansible to verify this. I can try that during weekend or next week.

**Comment by moserhans** [comment]
Playbook:
```
  - name: ensure resource 'ClusterIP' of 'IPaddr2' type exists an has 30 second monitor interval
    pcs_resource: name='ClusterIP' resource_type='IPaddr2' options='ip=172.30.8.199 op monitor interval=30'

  - name: ensure that resource with name 'ClusterIP' is not present
    pcs_resource: name='ClusterIP' state='absent'

  - name: ensure resource 'ClusterIP' of 'IPaddr2' type exists an has 30 second monitor interval
    pcs_resource: name='ClusterIP' resource_type='IPaddr2' options='ip=172.30.8.199 op monitor interval=130'
```

Playbook run:
```
TASK: [ensure resource 'ClusterIP' of 'IPaddr2' type exists an has 30 second monitor interval] ***
ok: [cluster4.example.com]
ok: [cluster1.example.com]
ok: [cluster3.example.com]
ok: [cluster2.example.com]

TASK: [ensure that resource with name 'ClusterIP' is not present] *************
changed: [cluster3.example.com]
changed: [cluster1.example.com]
changed: [cluster4.example.com]
changed: [cluster2.example.com]

TASK: [ensure resource 'ClusterIP' of 'IPaddr2' type exists an has 30 second monitor interval] ***
changed: [cluster4.example.com]
failed: [cluster1.example.com] => {"failed": true}
msg: Failed to create resource: Assumed agent name 'ocf:heartbeat:IPaddr2' (deduced from 'IPaddr2')

failed: [cluster2.example.com] => {"failed": true}
msg: Failed to create resource: Assumed agent name 'ocf:heartbeat:IPaddr2' (deduced from 'IPaddr2')

failed: [cluster3.example.com] => {"failed": true}
msg: Failed to create resource: Assumed agent name 'ocf:heartbeat:IPaddr2' (deduced from 'IPaddr2')
```

The result is:
`[root@cluster2 ~]# pcs resource show ClusterIP
 Resource: ClusterIP (class=ocf provider=heartbeat type=IPaddr2)
  Attributes: ip=172.30.8.199
  Operations: monitor interval=130 (ClusterIP-monitor-interval-130)
              start interval=0s timeout=20s (ClusterIP-start-interval-0s)
              stop interval=0s timeout=20s (ClusterIP-stop-interval-0s)`

The result is fine. The playbook failing for the other than the first node not so much, but OK.
To get a real change instead of delete-add would be great.

**Comment by moserhans** [comment]
I think there is no difference in check mode:
```
failed: [cluster4.example.com] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1516872771.02-152788037928624/pcs_resource", line 1860, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1516872771.02-152788037928624/pcs_resource", line 201, in main
    rc, diff = compare_resources(module, resource, clean_resource)
  File "/root/.ansible/tmp/ansible-tmp-1516872771.02-152788037928624/pcs_resource", line 110, in compare_resources
    'before': to_native(b('').join(n3_file.readlines())),
NameError: global name 'to_native' is not defined
OpenSSH_6.6.1, OpenSSL 1.0.1i-fips 6 Aug 2014
debug1: Reading configuration data /home/foo/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 20: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to cluster4.example.com closed.
```

**Comment by OndrejHome** [comment]
thank you for testing. I was expecting the add-delete-add to work just wanted to confirm that values are not a problem. --check seems to fail in same place as normal execution. I will have work on this.

**Comment by OndrejHome** [comment]
Hi @moserhans,
I was able to reproduce this with ansible-1.9.2 on Centos 7.4. Seems that function 'to_native' was introduced in ansible-2.2 and I was not checking if it is available. I'm using the function to make the 'diff' formatting pretty. In ansible-1.9.2 there is not '--diff' option so this should be needed there at all. If you try newer version of ansible you can try the '--check --diff' on resource that should be updated and you will get a "diff of changes in pacemaker CIB xml file" that are between current configuration and what the modules would like to use.

Change was introduced in commit ca22d2c that is now in 'develop' branch. Could you please let me know if the pcs_resource.py modules work after this change correctly also on your system with ansible-1.9.4?

**Comment by OndrejHome** [comment]
Hi @moserhans,
Could you please let me know if the changes in 'develop' branch resolved the problem also on your system? 
If I don't here from you within 2 weeks I will close this issue and the change will be merged to 'master' later if there are no conflicts.

**Comment by OndrejHome** [comment]
This is now part of 'master' branch and version 'v12' of 'OndrejHome.pcs-modules-2'. I will now close this Issue as I haven't heard from you for some time and I was able to test this in my testing environment to fix the problem. Feel free to re-open this issue if this still doesn't work in your environment.

**Comment by moserhans** [comment]
Sorry for the delay! :(

The check run ist fine now. Thank you for fixing this!

**Comment by OndrejHome** [comment]
Thank you @moserhans for reporting and confirming that it works for you!
